fix: max guess limit and guess count display
pavo-etc/minecraftle pull request #19
Opened 2023-11-15 16:13 UTC by TheVanadium

Fixes #18 

Limits the total amount of guesses to 10, as it should
Adds a catch to ensure the lose message does not show up if the game is won on the same turn the guess limit is reached
Limits updating the "guess-counter" div when the player has won; there is no additional increment in the guess count to display

2023-11-17 02:06 UTC, pavo-etc commented
Will test soon

2023-11-18 02:33 UTC, pavo-etc requested changes

2023-11-18 02:33 UTC, pavo-etc commented on app/static/js/processGuess.js
> +function min(a, b) {
Can just use Math.min(), don't need this function

2023-11-18 02:33 UTC, pavo-etc commented
Seems all good in testing, just remove the min function and I'll merge it

2023-11-18 02:47 UTC, TheVanadium commented
> Seems all good in testing, just remove the min function and I'll merge it

Done

2023-11-18 04:59 UTC, pavo-etc approved these changes

2023-11-18 04:59 UTC, merged