add functional clear button try
pavo-etc/minecraftle pull request #26
Opened 2023-12-06 16:07 UTC by JetShen

Fix: [issue ](https://github.com/pavo-etc/minecraftle/issues/11)

https://github.com/pavo-etc/minecraftle/assets/62623196/06aa1871-e7b9-4ad0-b723-faeba7fda557

2023-12-07 23:26 UTC, TheVanadium requested changes
Fix grammar on code doc - lines 332 and 333

2023-12-07 23:27 UTC, TheVanadium requested changes
I think it would look better aesthetically and intuitively if the guess counter was on the bottom. That way, all the crafting table-interaction tools are grouped, instead of divided by the counter.

2023-12-07 23:31 UTC, TheVanadium commented on app/static/js/init.js
> +  let lastTable = craftingTables.length - 1;
`currentTable` might be a better name here

2023-12-07 23:35 UTC, JetShen commented
> I think it would look better aesthetically and intuitively if the guess counter was on the bottom. That way, all the crafting table-interaction tools are grouped, instead of divided by the counter. However, it's up to @pavo-etc

You mean like this?

![image](https://github.com/pavo-etc/minecraftle/assets/62623196/2ae7a357-769a-4866-a696-96a5b01fb00b)

2023-12-07 23:38 UTC, pavo-etc commented
I think a better design would be to have the guess counter and clear button on the same line, but on opposite sides.

2023-12-07 23:41 UTC, TheVanadium commented on app/static/js/init.js
> +      slot.removeAttribute("style");
This should use the `setSlotBackground` function for consistency with other functions

2023-12-07 23:47 UTC, TheVanadium commented
> > I think it would look better aesthetically and intuitively if the guess counter was on the bottom. That way, all the crafting table-interaction tools are grouped, instead of divided by the counter. However, it's up to @pavo-etc
> 
> You mean like this?
> 
> ![image](https://private-user-images.githubusercontent.com/62623196/288919893-2ae7a357-769a-4866-a696-96a5b01fb00b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5OTMwODksIm5iZiI6MTcwMTk5Mjc4OSwicGF0aCI6Ii82MjYyMzE5Ni8yODg5MTk4OTMtMmFlN2EzNTctNzY5YS00ODY2LWE2OTYtOTZhNWIwMWZiMDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDIzNDYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3YmQzOTExMTU4YzQ5MzdkZmNhMWM2ZTU4N2Q2NTVjMDAxZmZkNmI5MmUzMDlhMjVmYzc4ZjdjOWM5MGJlMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LwADj98NipaPPlshgjvt2my4vviJO42BDLOc_F36pzc)

Yeah I like that, but go with @pavo-etc since he's here

2023-12-07 23:50 UTC, JetShen commented on app/static/js/init.js
> + * Clear the lats crafting table
Could you give me an idea of how I would do the message for documentation?

2023-12-07 23:51 UTC, JetShen commented
> I think a better design would be to have the guess counter and clear button on the same line, but on opposite sides.
@TheVanadium 
do you like it this way?

![image](https://github.com/pavo-etc/minecraftle/assets/62623196/bf425566-acf1-4d4e-a517-ae57366a4562)

2023-12-07 23:55 UTC, TheVanadium commented
> > I think a better design would be to have the guess counter and clear button on the same line, but on opposite sides.
> > @TheVanadium
> > do you like it this way?
> 
> ![image](https://private-user-images.githubusercontent.com/62623196/288921990-bf425566-acf1-4d4e-a517-ae57366a4562.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5OTMzOTcsIm5iZiI6MTcwMTk5MzA5NywicGF0aCI6Ii82MjYyMzE5Ni8yODg5MjE5OTAtYmY0MjU1NjYtYWNmMS00ZDRlLWE1MTctYWU1NzM2NmE0NTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDIzNTEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNjY1ODliM2RkNGU3ZWRkNmUwMzBhMTM4ZDY4N2E0ZjRlOTNmMDJiOTllOWNlMGZiZjk3ZDM1ODFmNjM4ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6V6C23skUIWgfrANGINz4FGnto4dgzRjX3n-u670Qu0)

Personally I prefer the `Clear Table` button on the left because the left is the side of the crafting table the user interacts with. On the right, the average mouse path is diagonal, which feel strange. However, ultimately up to @pavo-etc

2023-12-08 00:11 UTC, JetShen commented
I forgot to change this part 💀 

![image](https://github.com/pavo-etc/minecraftle/assets/62623196/64b938be-bd3e-4563-82d3-b38d4f72e4a9)

2023-12-08 00:14 UTC, TheVanadium commented
Can you figure out a way to disable the function when the game is over?
<img src="https://github.com/pavo-etc/minecraftle/assets/53013571/dc9fc35c-8336-422e-b0d0-10ab4f1e6e50" width="200" height="350">

2023-12-08 00:15 UTC, JetShen commented
> Can you figure out a way to disable the function when the game is over? <img alt="" width="200" height="350" src="https://private-user-images.githubusercontent.com/53013571/288925717-dc9fc35c-8336-422e-b0d0-10ab4f1e6e50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5OTQ3NDgsIm5iZiI6MTcwMTk5NDQ0OCwicGF0aCI6Ii81MzAxMzU3MS8yODg5MjU3MTctZGM5ZmMzNWMtODMzNi00MjJlLWIwZDAtMTBhYjRmMWU2ZTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAwMTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyYmI0NzliZjI1MDAyNDIwNTBjOTAwMTAwZWI0NmY0OGZjYjM4YzQ1ZmQ2ZGM2YjAyNDhlMTM3ZDdhOGVhZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VgYkEj2uIFPcNMcTQP3Rdzkdqy38AN04KuLOfcLUjPI">

Do you mean that the button disappears and the attempts remain in the center?

2023-12-08 00:17 UTC, TheVanadium commented
I think preferably the button click should just do nothing. It should be something like a global variable that tracks whether or not the game is over yet, but I don't know if one exists so far.

2023-12-08 00:20 UTC, JetShen commented
there is no such variable, what could be done is to disable/remove the button in the gain/loss functions.

2023-12-08 06:32 UTC, TheVanadium requested changes
`clearbutton` should be `gameIsFinished`, and `gameIsFinished` should be false by default, as the game starts unfinished, then set to true in the `winner()` and `loser()` functions.

2024-01-23 22:05 UTC, closed without merging